// NOTIFICATIONS
export const NOTIFICATION_ADD = 'ADD_NOTIFICATION';
export const NOTIFICATIONS_READ = 'SET_NOTIFICATIONS_READ';
export const SNACK_ADD = 'ADD_SNACK';
export const SNACK_CLOSE = 'CLOSE_SNACK';

// AUTH
export const ACCOUNT_CHECK_IF_EMAIL_EXISTS = 'CHECK_IF_EMAIL_EXISTS';
export const ACCOUNT_CREATE_NEW_USER = 'CREATE_NEW_USER';
export const ACCOUNT_LOG_IN_WITH_PASSWORD = 'LOG_IN_WITH_PASSWORD';
export const ACCOUNT_SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL';
