// NOTIFICATIONS
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_SNACK = 'ADD_SNACK';
export const CLOSE_SNACK = 'CLOSE_SNACK';
export const SET_NOTIFICATIONS_READ = 'SET_NOTIFICATIONS_READ';

// AUTH
export const CHECK_IF_EMAIL_EXISTS = 'CHECK_IF_EMAIL_EXISTS';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOG_IN_WITH_PASSWORD = 'LOG_IN_WITH_PASSWORD';
export const SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL';
